# Backs up data from the tables into a folder called backups.
USE mothy;

SELECT * FROM Users
INTO OUTFILE '/tmp/User.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Song
INTO OUTFILE '/tmp/Song.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Vocaloid
INTO OUTFILE '/tmp/Vocaloid.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Persona
INTO OUTFILE '/tmp/Persona.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Appear
INTO OUTFILE '/tmp/Role.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Album
INTO OUTFILE '/tmp/Album.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Track
INTO OUTFILE '/tmp/Track.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Series
INTO OUTFILE '/tmp/Series.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Part
INTO OUTFILE '/tmp/Part.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Canon
INTO OUTFILE '/tmp/Canon.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Video
INTO OUTFILE '/tmp/Video.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

SELECT * FROM Artist
INTO OUTFILE '/tmp/Artist.csv'
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';
